
OLED_ENABLE = yes
OLED_DRIVER = ssd1306
ENCODER_ENABLE = yes
RGBLIGHT_ENABLE = yes

CONSOLE_ENABLE = no
EXTRAKEY_ENABLE = no

SWAP_HANDS_ENABLE = no
COMBO_ENABLE = no
GRAVE_ESC_ENABLE = no
MAGIC_ENABLE = no
BOOTMAGIC_ENABLE = no
COMMAND_ENABLE = no

#Link time optimise sise
LTO_ENABLE = yes
